name: base
channels:
  - defaults
dependencies:
  - asn1crypto=1.3.0=py37_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - conda=4.8.2=py37_0
  - conda-package-handling=1.6.0=py37h1de35cc_0
  - cryptography=2.8=py37ha12b0ac_0
  - idna=2.8=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1d=h1de35cc_4
  - pip=20.0.2=py37_1
  - pycosat=0.6.3=py37h1de35cc_0
  - pycparser=2.19=py37_0
  - pyopenssl=19.1.0=py37_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h359304d_2
  - python.app=2=py37_10
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py37_1
  - ruamel_yaml=0.15.87=py37h1de35cc_0
  - setuptools=45.2.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tqdm=4.42.1=py_0
  - urllib3=1.25.8=py37_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/mariocatuogno/miniconda

